In [76]:
import numpy as np

In [77]:
def m_init(shape,value=0):
    return np.full(shape,value)

m_init((3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [78]:
import pandas as pd

In [79]:
s = pd.Series([1,2,3,4,5], index=["A","B","C","D","E"])
s

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [80]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,777,"xyz"]]

# data = {'col1':[1,2,3,4],
#         'col2':[444,555,666,444],
#         'col3':['abc','def','ghi','xyz']}

In [81]:
columns=["col1","cal2","cal3"]
df = pd.DataFrame(data,columns=["col1","cal2","cal3"])
display(df)
df.columns = ["id","salary","dep"]
display(df)
df.index = ["d1","d2","d3","d4"]
display(df)

   col1  cal2 cal3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   777  xyz

   id  salary  dep
0   1     444  abc
1   2     555  def
2   3     666  ghi
3   4     777  xyz

    id  salary  dep
d1   1     444  abc
d2   2     555  def
d3   3     666  ghi
d4   4     777  xyz

In [82]:
df.dtypes

id        int64
salary    int64
dep         str
dtype: object

In [83]:
df['dep'].dtype

In [84]:
df['dep'] = df['dep'].astype('category')

In [85]:
df.dtypes

id           int64
salary       int64
dep       category
dtype: object

In [86]:
col_cat = ['id','salary']
df[col_cat] = df[col_cat].astype('category')

In [87]:
df.dtypes

id        category
salary    category
dep       category
dtype: object

In [88]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]

# data = {'col1':[1,2,3,4],
#         'col2':[444,555,666,444],
#         'col3':['abc','def','ghi','xyz']}

In [89]:
df = pd.DataFrame(data,columns=["col1","col2","col3"])

In [90]:
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [91]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='str')

In [92]:
df.col2.unique()

array([444, 555, 666])

In [93]:
classification = df.col2.nunique()
classification

3

In [94]:
df['col2'].min()

np.int64(444)

In [95]:
def get_range(df):
    return df.max() - df.min()
get_range(df.col1)

np.int64(3)

In [96]:
df.col2.value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [98]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      str
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [101]:
x1 = df.col2.values
type(x1)

numpy.ndarray

In [102]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 444, 'xyz']], dtype=object)

In [103]:
df.replace(555,"yousef")

   col1    col2 col3
0     1     444  abc
1     2  yousef  def
2     3     666  ghi
3     4     444  xyz